### PR TITLE
Official JIRA plugin-like message formatting, Issue-key regex now case-insensitive, and Configurable prefix text

### PR DESCRIPTION
**Pull request by krishnanmk**
#### Code Changes
- Changed key detection to be case-insensitive
- Formatting changed to make it look more like official JIRA plugin
- Removed :jira: emoji from message because the Bot would already have
  a similar emoji, so it seemed redundant
- added `creator` as independent option in `issueDetailsToShow`
- added custom prefix text as configurable option
#### README Changes
- Edited some info in existing Configuration description section
- Added new config info
- Added two more to-do items

### CODE REVIEW

**Comment by krishnanmk** [comment]
screen shot 2015-11-22 at 1 10 37 am

**Comment by krishnanmk** [comment]
Hi @gsingers , would you be interested in the changes submitted? Thanks.

**Comment by gsingers** [comment]
Merged.  Thanks @krislogy

**Comment by krishnanmk** [comment]
Awesome! Thank you too.

**Pull request merged**
